
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.java.compiler;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR_CONST = 23;
  public static final int WHEN = 45;
  public static final int DOFOR = 51;
  public static final int ASSIGNDECL = 56;
  public static final int CHAR = 14;
  public static final int GE = 34;
  public static final int UMINUS = 29;
  public static final int OTHER = 47;
  public static final int DOUBLE_CONST = 22;
  public static final int DOUBLE = 12;
  public static final int SEMI = 53;
  public static final int INT = 10;
  public static final int OUT = 59;
  public static final int RBRAC = 42;
  public static final int FOR = 52;
  public static final int MINUS = 26;
  public static final int REF = 8;
  public static final int OUTNL = 60;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int LT = 35;
  public static final int RPAR = 40;
  public static final int IN = 58;
  public static final int OR = 31;
  public static final int COMMA = 50;
  public static final int BOOL = 11;
  public static final int DIV = 28;
  public static final int BEGIN = 16;
  public static final int LOOP = 46;
  public static final int PLUS = 25;
  public static final int ASSIGN = 54;
  public static final int IF = 2;
  public static final int ID = 57;
  public static final int DOT = 48;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int INT_CONST = 21;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int PROGRAM = 15;
  public static final int PIPE = 49;
  public static final int EQ = 37;
  public static final int MAPSUM = 18;
  public static final int TIMES = 27;
  public static final int COLON = 55;
  public static final int ELSE = 4;
  public static final int WHILE = 5;
  public static final int LET = 43;
  public static final int THEN = 3;
  public static final int NE = 38;
  public static final int END = 17;
  public static final int LPAR = 39;
  public static final int STRING = 13;
  public static final int DEF = 9;
  public static final int LBRAC = 41;
  public static final int FALSE = 20;
  public static final int STRING_CONST = 24;
  public static final int GT = 33;
  public static final int DO = 6;
  public static final int GO = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "RETURN",
  "REF",
  "DEF",
  "INT",
  "BOOL",
  "DOUBLE",
  "STRING",
  "CHAR",
  "PROGRAM",
  "BEGIN",
  "END",
  "MAPSUM",
  "TRUE",
  "FALSE",
  "INT_CONST",
  "DOUBLE_CONST",
  "CHAR_CONST",
  "STRING_CONST",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "AND",
  "OR",
  "NOT",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "LPAR",
  "RPAR",
  "LBRAC",
  "RBRAC",
  "LET",
  "GO",
  "WHEN",
  "LOOP",
  "OTHER",
  "DOT",
  "PIPE",
  "COMMA",
  "DOFOR",
  "FOR",
  "SEMI",
  "ASSIGN",
  "COLON",
  "ASSIGNDECL",
  "ID",
  "IN",
  "OUT",
  "OUTNL"
  };
}

